### ISSUE TITLE
Add support for photos and documents on frontend

### ISSUE THREAD

**Issue by josephmoore99** [cs481-ekh/s22-beima#276]
As a user, I need to be able to upload a device image and any additional documents so that I can have all relevant device information in once place.

**Tasks**
- [x] #280
- [x] #281
- [x] #282

**Acceptance Criteria:**
- [x] Given a new device, when adding a photo, then the photo should be stored when adding a new device.
- [x] Given a new device, when adding additional documents, then the documents should be stored when adding a new device.
- [x] Given a device, when navigating to the device view page, then the photo should be displayed and the additional documents file names should be displayed.
- [x] Given a device, when updating the photo, then the photo should be updated in the database.
- [x] Given a device, when deleting the photo, then the photo should be deleted in the database.
- [x] - [ ] Given a device, when updating the additional documents, then the additional documents should be updated in the database.
- [ ] Given a device, when deleting the additional documents or a single document, then the document(s) should be deleted in the database.
