### ISSUE TITLE
Add frontend authentication functionality

### ISSUE THREAD

**Issue by josephmoore99** [cs481-ekh/s22-beima#277]
As a user, I need to be able to enter my username and password and be logged in correctly so that only authenticated users have access to BEIMA. 

**Tasks**
- [x] #291
- [x] #292
- [x] #367
- [x] #368
- [x] #369
- [x] #370

See task #291 for a list of resources about JWT and how to use it.

**Acceptance Criteria:**
- [x] Given a correct username and password, when login is attempted, then the user has access to BEIMA.
- [x] Given an incorrect username and password, when login is attempted, then the user does not has access to BEIMA.
- [x] Given an incorrect username and password, when login is attempted, then the user is notified about incorrect login on login page.
